version: '3.8'

services:
  # Redis service for Bull queues
  redis:
    image: redis:7-alpine
    container_name: arbitrage-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - arbitrage-network

  # Futures Arbitrage Bot
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: arbitrage-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Application
      NODE_ENV: production
      PORT: 3000
      
      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      
      # Telegram Bot (customize these)
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-your_telegram_bot_token_here}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:--123456789}
      
      # Exchange API Keys (optional for public endpoints)
      BINANCE_API_KEY: ${BINANCE_API_KEY:-}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET:-}
      BYBIT_API_KEY: ${BYBIT_API_KEY:-}
      BYBIT_API_SECRET: ${BYBIT_API_SECRET:-}
      MEXC_API_KEY: ${MEXC_API_KEY:-}
      MEXC_API_SECRET: ${MEXC_API_SECRET:-}
      GATEIO_API_KEY: ${GATEIO_API_KEY:-}
      GATEIO_API_SECRET: ${GATEIO_API_SECRET:-}
      LBANK_API_KEY: ${LBANK_API_KEY:-}
      LBANK_API_SECRET: ${LBANK_API_SECRET:-}
      
      # Arbitrage Configuration
      ARBITRAGE_THRESHOLD_PERCENT: ${ARBITRAGE_THRESHOLD_PERCENT:-0.7}
      COOLDOWN_MINUTES: ${COOLDOWN_MINUTES:-5}
      MIN_PROFIT_USD: ${MIN_PROFIT_USD:-10}
      
      # Trading Pairs
      TRADING_PAIRS: ${TRADING_PAIRS:-BTC/USDT,ETH/USDT,BNB/USDT}
      
      # New Listings Configuration
      NEW_LISTING_CHECK_INTERVAL: ${NEW_LISTING_CHECK_INTERVAL:-30}
      NEW_LISTING_THRESHOLD_HOURS: ${NEW_LISTING_THRESHOLD_HOURS:-24}
      
    volumes:
      - app_logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - arbitrage-network

volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  arbitrage-network:
    driver: bridge 