version: '3.8'

# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose for development

services:
  app:
    build:
      target: builder  # Use builder stage for development
    container_name: arbitrage-bot-dev
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - app_logs:/app/logs
    command: ["yarn", "start:dev"]  # Use development start command
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    
  # Redis with debugging enabled for development
  redis:
    container_name: arbitrage-redis-dev
    ports:
      - "6379:6379"  # Expose for external tools
    volumes:
      - redis_data_dev:/data

volumes:
  redis_data_dev:
    driver: local 